server:
  port: 8093

spring:
  application:
    name: msvc-alarmas
  data:
    mongodb:
      database: alarmas_db
      uri: mongodb+srv://invernaderosamigochas:D2YQsIyoTsPrNeLf@invernaderoamigochas.1yweuva.mongodb.net/?retryWrites=true&w=majority&appName=InvernaderoAmigochas
      auto-index-creation: true
  cloud:
    config:
      enabled: false

grpc:
  server:
    port: 9093
    security:
      enabled: true
      certificate-chain: classpath:certs/alarmas-service.crt
      private-key: classpath:certs/alarmas-service.pem
  client:
    anomalyzer:
      address: static://anomalyzer-service:9094
      negotiation-type: TLS
      security:
        trust-cert-collection: classpath:certs/anomalyzer-service.cert.pem
      enable-keep-alive: true

management:
  tracing:
    sampling:
      probability: 1.0