services:
  lecturas-app:
    image: lecturas-imagen
    container_name: lecturas-service
    build:
      context: Microservicios/Lecturas
      dockerfile: Dockerfile
    ports:
      - "8091:8091"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb+srv://invernaderosamigochas:D2YQsIyoTsPrNeLf@invernaderoamigochas.1yweuva.mongodb.net/?retryWrites=true&w=majority&appName=InvernaderoAmigochas

  gestion-sensores-app:
    image: gestion-sensores-imagen
    container_name: gestion-sensores-service
    build:
      context: Microservicios/GestionSensores
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
      - "9090:9090"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb+srv://invernaderosamigochas:D2YQsIyoTsPrNeLf@invernaderoamigochas.1yweuva.mongodb.net/?retryWrites=true&w=majority&appName=InvernaderoAmigochas

  alarmas-app:
    image: alarmas-imagen
    container_name: alarmas-service
    build:
      context: Microservicios/Alarmas
      dockerfile: Dockerfile
    ports:
      - "8093:8093"
      - "9093:9093"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb+srv://invernaderosamigochas:D2YQsIyoTsPrNeLf@invernaderoamigochas.1yweuva.mongodb.net/?retryWrites=true&w=majority&appName=InvernaderoAmigochas

  reportes-anomalias-app:
    image: reportes-anomalias-imagen
    container_name: reportes-anomalias-service
    build:
      context: Microservicios/ReportesAnomalias
      dockerfile: Dockerfile
    ports:
      - "8092:8092"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb+srv://invernaderosamigochas:D2YQsIyoTsPrNeLf@invernaderoamigochas.1yweuva.mongodb.net/?retryWrites=true&w=majority&appName=InvernaderoAmigochas
    command: sh -c "sleep 50 && java -jar /app/app.jar"

  anomalyzer-app:
    image: anomalyzer-imagen
    container_name: anomalyzer-service
    build:
      context: Anomalyzer
      dockerfile: Dockerfile
    ports:
      - "8094:8094"
      - "9094:9094"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb+srv://invernaderosamigochas:D2YQsIyoTsPrNeLf@invernaderoamigochas.1yweuva.mongodb.net/?retryWrites=true&w=majority&appName=InvernaderoAmigochas

  alarmator-app:
    image: alarmator-imagen
    container_name: alarmator-service
    build:
      context: Alarmator
      dockerfile: Dockerfile
    ports:
      - "8097:8097"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb+srv://invernaderosamigochas:D2YQsIyoTsPrNeLf@invernaderoamigochas.1yweuva.mongodb.net/?retryWrites=true&w=majority&appName=InvernaderoAmigochas

  login-app:
    image: login-imagen
    container_name: login-service
    build:
      context: Microservicios/Login
      dockerfile: Dockerfile
    ports:
      - "8095:8095"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb+srv://invernaderosamigochas:D2YQsIyoTsPrNeLf@invernaderoamigochas.1yweuva.mongodb.net/?retryWrites=true&w=majority&appName=InvernaderoAmigochas

  autenticacion-app:
    image: autenticacion-imagen
    container_name: autenticacion-service
    build:
      context: Autenticacion
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
      - "9100:9100"

  api-gateway-app:
    image: api-gateway-imagen
    container_name: api-gateway-service
    build:
      context: APIGateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  simulador-app:
    image: simulador-imagen
    container_name: simulador
    build:
      context: Simulador
      dockerfile: Dockerfile
    depends_on:
      - mosquitto

  informes-app:
    image: informes-imagen
    container_name: informes-service
    build:
      context: Informes
      dockerfile: Dockerfile
    ports:
      - "8099:8099"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb+srv://invernaderosamigochas:D2YQsIyoTsPrNeLf@invernaderoamigochas.1yweuva.mongodb.net/?retryWrites=true&w=majority&appName=InvernaderoAmigochas
    command: sh -c "sleep 50 && java -jar /app/app.jar"

  exposicion-datos-app:
    image: exposicion-datos-imagen
    container_name: exposicion-datos-service
    build:
      context: ExposicionDatos
      dockerfile: Dockerfile
    ports:
      - "8096:8096"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb+srv://invernaderosamigochas:D2YQsIyoTsPrNeLf@invernaderoamigochas.1yweuva.mongodb.net/?retryWrites=true&w=majority&appName=InvernaderoAmigochas
    command: sh -c "sleep 50 && java -jar /app/app.jar"

  gateway-app:
    image: gateway-imagen
    container_name: gateway
    build:
      context: Gateway
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - mosquitto

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
      
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf