server:
  port: 8091

spring:
  application:
    name: msvc-lecturas
  data:
    mongodb:
      database: lecturas_db
      uri: mongodb+srv://invernaderosamigochas:D2YQsIyoTsPrNeLf@invernaderoamigochas.1yweuva.mongodb.net/?retryWrites=true&w=majority&appName=InvernaderoAmigochas

grpc:
  client:
    gestion-sensores:
      address: static://localhost:50051
      negotiation-type: plaintext
      enable-keep-alive: true


management:
  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
