server:
  port: 8090

spring:
  application:
    name: msvc-gestion-sensores
  data:
    mongodb:
      database: gestion_sensores_db
      uri: mongodb+srv://invernaderosamigochas:D2YQsIyoTsPrNeLf@invernaderoamigochas.1yweuva.mongodb.net/?retryWrites=true&w=majority&appName=InvernaderoAmigochas
      auto-index-creation: true

grpc:
  server:
    port: 9090
  client:
    estado-sensores:
      address: static://localhost:50051
      negotiation-type: plaintext
      enable-keep-alive: true

management:
  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
