server:
  port: 8092

spring:
  application:
    name: msvc-reportes-anomalias
  data:
    mongodb:
      database: reportes_anomalias_db
      uri: mongodb+srv://invernaderosamigochas:D2YQsIyoTsPrNeLf@invernaderoamigochas.1yweuva.mongodb.net/?retryWrites=true&w=majority&appName=InvernaderoAmigochas

management:
  tracing:
    sampling:
      probability: 1.0
