server:
  port: 8080

spring:
  application:
    name: msvc-api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: msvc-gestion-sensores
          uri: lb://msvc-gestion-sensores
          predicates:
            - Path=/api/v1/gestionSensores/**
        - id: msvc-alarmas
          uri: lb://msvc-alarmas
          predicates:
            - Path=/api/v1/alarmas/**
        - id: msvc-lecturas
          uri: lb://msvc-lecturas
          predicates:
            - Path=/api/v1/lecturas/**
        - id: msvc-reportes-anomalias
          uri: lb://msvc-reportes-anomalias
          predicates:
            - Path=/api/v1/reportesAnomalias/**
        - id: msvc-informes
          uri: lb://msvc-informes
          predicates:
            - Path=/api/v1/informes/**
        - id: msvc-login
          uri: lb://MSVC-LOGIN
          predicates:
            - Path=/api/v1/login

#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: "http://localhost:5174"
#            allowedMethods: "*"
#            allowedHeaders: "*"
#            allowCredentials: true

management:
  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
