server:
  port: 8080

spring:
  application:
    name: msvc-api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: msvc-gestion-sensores
          uri: lb://msvc-gestion-sensores
          predicates:
            - Path=/api/v1/gestionSensores/**

management:
  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
