server:
  port: 8090

spring:
  application:
    name: msvc-gestion-sensores
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gestion_sensores
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: mysql
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: always
      data-locations: classpath:static/import.sql

management:
  tracing:
    sampling:
      probability: 1.0

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka