server:
  port: 8093

spring:
  application:
    name: msvc-alarmas
  data:
    mongodb:
      database: alarmas_db
      uri: mongodb+srv://invernaderosamigochas:D2YQsIyoTsPrNeLf@invernaderoamigochas.1yweuva.mongodb.net/?retryWrites=true&w=majority&appName=InvernaderoAmigochas
      auto-index-creation: true

grpc:
  server:
    port: 9093
  client:
    anomalyzer:
      address: static://localhost:50054
      negotiation-type: plaintext
      enable-keep-alive: true

management:
  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true