server:
  port: 8096

spring:
  application:
    name: msvc-exposicion-datos
  data:
    mongodb:
      database: exposicion_datos_db
      uri: mongodb+srv://invernaderosamigochas:D2YQsIyoTsPrNeLf@invernaderoamigochas.1yweuva.mongodb.net/?retryWrites=true&w=majority&appName=InvernaderoAmigochas

management:
  tracing:
    sampling:
      probability: 1.0
