server:
  port: 8095

spring:
  application:
    name: msvc-login
  data:
    mongodb:
      database: usuarios_bd
      uri: mongodb+srv://invernaderosamigochas:D2YQsIyoTsPrNeLf@invernaderoamigochas.1yweuva.mongodb.net/?retryWrites=true&w=majority&appName=InvernaderoAmigochas

management:
  tracing:
    sampling:
      probability: 1.0
