server:
  port: 8091

spring:
  application:
    name: msvc-lecturas
  data:
    mongodb:
      database: lecturas_db
      uri: mongodb+srv://invernaderosamigochas:D2YQsIyoTsPrNeLf@invernaderoamigochas.1yweuva.mongodb.net/?retryWrites=true&w=majority&appName=InvernaderoAmigochas

grpc:
  server:
    port: 9091
  client:
    gestion-sensores:
      address: static://localhost:50050
      negotiation-type: plaintext
      enable-keep-alive: true

management:
  tracing:
    sampling:
      probability: 1.0
