server:
  port: 8095

spring:
  application:
    name: msvc-login
  data:
    mongodb:
      database: usuarios_bd
      uri: mongodb+srv://invernaderosamigochas:D2YQsIyoTsPrNeLf@invernaderoamigochas.1yweuva.mongodb.net/?retryWrites=true&w=majority&appName=InvernaderoAmigochas

jwt:
  secret: "unaClaveSecretaMuyLargaYSeguraParaFirmarLosTokensJWT"
  expiration: 3600000  # 1 hora

management:
  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
