server:
  port: 8094

spring:
  application:
    name: msvc-informes
  data:
    mongodb:
      database: lecturas_db
      uri: mongodb+srv://invernaderosamigochas:D2YQsIyoTsPrNeLf@invernaderoamigochas.1yweuva.mongodb.net/?retryWrites=true&w=majority&appName=InvernaderoAmigochas

grpc:
  client:
    gestion-sensores-service:
      address: static://localhost:9090
      negotiation-type: TLS
      security:
        trust-cert-collection: classpath:certs/localhost.cert.pem
      enable-keep-alive: true

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    org.springframework.data.mongodb.core: DEBUG
    org.mongodb.driver: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
