server:
  port: 8097

spring:
  application:
    name: svc-autenticacion

jwt:
  secret: "unaClaveSecretaMuyLargaYSeguraParaFirmarLosTokensJWT"
  expiration: 3600000  # 1 hora

management:
  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true