server:
  port: 8094

spring:
  application:
    name: anomalyzer
  data:
    mongodb:
      anomalyzer:
        uri: mongodb+srv://invernaderosamigochas:D2YQsIyoTsPrNeLf@invernaderoamigochas.1yweuva.mongodb.net/anomalyzer_db?retryWrites=true&w=majority&appName=InvernaderoAmigochas
      alarmas:
        uri: mongodb+srv://invernaderosamigochas:D2YQsIyoTsPrNeLf@invernaderoamigochas.1yweuva.mongodb.net/alarmas_db?retryWrites=true&w=majority&appName=InvernaderoAmigochas


grpc:
  server:
    port: 9094
    security:
      enabled: true
      certificate-chain: classpath:certs/anomalyzer-service.crt
      private-key: classpath:certs/anomalyzer-service.pem
  client:
    alarmas:
      address: static://alarmas-service:9093
      negotiation-type: TLS
      security:
        trust-cert-collection: classpath:certs/alarmas-service.cert.pem
      enable-keep-alive: true

management:
  tracing:
    sampling:
      probability: 1.0
