server:
  port: 8094

spring:
  application:
    name: anomalyzer
  data:
    mongodb:
      database: anomalias_db
      uri: mongodb+srv://invernaderosamigochas:D2YQsIyoTsPrNeLf@invernaderoamigochas.1yweuva.mongodb.net/?retryWrites=true&w=majority&appName=InvernaderoAmigochas

grpc:
  server:
    port: 9094
  client:
    gestion-sensores:
      address: static://localhost:50051
      negotiation-type: plaintext
      enable-keep-alive: true
    alarmas:
      address: static://localhost:50053
      negotiation-type: plaintext
      enable-keep-alive: true

management:
  tracing:
    sampling:
      probability: 1.0
