server:
  port: 8094

spring:
  application:
    name: anomalyzer
  data:
    mongodb:
      database: anomalyzer_db
      uri: mongodb+srv://invernaderosamigochas:D2YQsIyoTsPrNeLf@invernaderoamigochas.1yweuva.mongodb.net/?retryWrites=true&w=majority&appName=InvernaderoAmigochas

grpc:
  server:
    port: 9094
    security:
      enabled: true
      certificate-chain: classpath:certs/localhost.crt
      private-key: classpath:certs/localhost.pem
  client:
    alarmas:
      address: static://localhost:9093
      negotiation-type: TLS
      security:
        trust-cert-collection: classpath:certs/localhost.cert.pem

management:
  tracing:
    sampling:
      probability: 1.0
