server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    config:
      enabled: false
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
              - "http://192.168.1.69:5173"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: svc-autenticacion
          uri: http://autenticacion-service:8100
          predicates:
            - Path=/auth/**

        - id: msvc-gestion-sensores
          uri: http://gestion-sensores-service:8090
          predicates:
            - Path=/api/v1/gestionSensores/**
          filters:
            - AuthenticationFilter

        - id: msvc-alarmas
          uri: http://alarmas-service:8093
          predicates:
            - Path=/api/v1/alarmas/**
          filters:
            - AuthenticationFilter

        - id: msvc-lecturas
          uri: http://lecturas-service:8091
          predicates:
            - Path=/api/v1/lecturas/**
          filters:
            - AuthenticationFilter

        - id: msvc-reportes-anomalias
          uri: http://reportes-anomalias-service:8092
          predicates:
            - Path=/api/v1/reportesAnomalias/**
          filters:
            - AuthenticationFilter

        - id: svc-informes
          uri: http://informes-service:8099
          predicates:
            - Path=/api/v1/informes/**
          filters:
            - AuthenticationFilter

        - id: msvc-login
          uri: http://login-service:8095
          predicates:
            - Path=/api/v1/login

management:
  tracing:
    sampling:
      probability: 1.0

# Configuración del cliente gRPC
grpc:
  client:
    autenticacion-service:
      address: static://autenticacion-service:9100
      negotiation-type: TLS
      security:
        trust-cert-collection: classpath:certs/autenticacion-service.cert.pem
      enable-keep-alive: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.web.cors: TRACE
    org.springframework.web.reactive: TRACE
    reactor.netty.http.server: DEBUG
