server:
  port: 8100

spring:
  application:
    name: svc-autenticacion
  cloud:
    config:
      enabled: false

grpc:
  server:
    port: 9100
  security:
    enabled: true
    certificate-chain: classpath:certs/autenticacion-service.crt
    private-key: classpath:certs/autenticacion-service.pem

jwt:
  secret: "unaClaveSecretaMuyLargaYSeguraParaFirmarLosTokensJWT"
  expiration: 3600000  # 1 hora

management:
  tracing:
    sampling:
      probability: 1.0