server:
  port: 8100

spring:
  application:
    name: svc-autenticacion
  cloud:
    config:
      enabled: false

grpc:
  server:
    port: 9100

jwt:
  secret: "unaClaveSecretaMuyLargaYSeguraParaFirmarLosTokensJWT"
  expiration: 3600000  # 1 hora

management:
  tracing:
    sampling:
      probability: 1.0