server:
  port: 8097

spring:
  application:
    name: alarmator
  mail:
    host: smtp.gmail.com
    port: 587
    username: bortcrab@gmail.com
    password: nrth kauw ldol omjj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

twilio:
  account-sid: ACc3eeeb0d42dd3e70b2a881f0a1161621
  auth-token: b472299536afb335b2d4d4660ae13a1b
  phone-number: +18145177553

management:
  tracing:
    sampling:
      probability: 1.0