server:
  port: 8091

spring:
  application:
    name: msvc-lecturas
  data:
    mongodb:
      database: lecturas_db
      uri: mongodb+srv://invernaderosamigochas:D2YQsIyoTsPrNeLf@invernaderoamigochas.1yweuva.mongodb.net/?retryWrites=true&w=majority&appName=InvernaderoAmigochas
  cloud:
    config:
      enabled: false

management:
  tracing:
    sampling:
      probability: 1.0